# Generated by Django 2.2.5 on 2019-12-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_user_hola'),
    ]

    operations = [
        migrations.CreateModel(
            name='barpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('slug', models.SlugField(default=1354297504, max_length=255, unique=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('dia', models.TextField()),
                ('code', models.CharField(max_length=5, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='postrelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('winer_code', models.CharField(max_length=20, verbose_name='Code to Retrieve')),
                ('status', models.CharField(choices=[('W', 'Winner'), ('R', 'Refused'), ('2BA', 'To_be_accepted'), ('F', 'Finished')], default='2BA', max_length=3)),
                ('code', models.CharField(max_length=5, null=True)),
                ('event', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.barpost')),
                ('person', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='fotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='image/')),
                ('updloader', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AddField(
            model_name='barpost',
            name='posts',
            field=models.ManyToManyField(blank=True, to='eventos.fotos', verbose_name='publicaciones'),
        ),
        migrations.AddField(
            model_name='barpost',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_barpost_users_+', to='accounts.user', verbose_name='list of users'),
        ),
        migrations.AddField(
            model_name='barpost',
            name='users_winners',
            field=models.ManyToManyField(blank=True, related_name='_barpost_users_winners_+', to='accounts.user', verbose_name='list of users Winners'),
        ),
    ]
