# Generated by Django 2.2.5 on 2019-12-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_hola'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('slug', models.SlugField(default=1354297504, max_length=255, unique=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('dia', models.TextField()),
                ('code', models.CharField(max_length=5, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('posts', models.ManyToManyField(blank=True, to='eventos.fotos', verbose_name='publicaciones')),
                ('users', models.ManyToManyField(blank=True, related_name='_eventpost_users_+', to='accounts.user', verbose_name='list of users')),
                ('users_winners', models.ManyToManyField(blank=True, related_name='_eventpost_users_winners_+', to='accounts.user', verbose_name='list of users Winners')),
            ],
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='event',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.eventpost'),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('W', 'Winner'), ('F', 'Finished'), ('R', 'Refused'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
        migrations.DeleteModel(
            name='barpost',
        ),
    ]
