# Generated by Django 2.2.5 on 2019-12-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20191225_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140726553188688, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('2BO', 'To_be_open'), ('F', 'Finished')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('F', 'Finished'), ('R', 'Refused'), ('W', 'Winner')], default='2BA', max_length=3),
        ),
    ]
