# Generated by Django 3.0.5 on 2020-04-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200423_0030'),
        ('eventos', '0003_auto_20200423_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
