# Generated by Django 2.2.5 on 2019-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20191225_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='dia',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='scoring',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('C', 'Close'), ('O', 'Open'), ('F', 'Finished'), ('2BO', 'To_be_open')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('W', 'Winner'), ('F', 'Finished'), ('R', 'Refused')], default='2BA', max_length=3),
        ),
    ]
