# Generated by Django 2.2.5 on 2019-12-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20191225_1954'),
        ('eventos', '0004_auto_20191225_1944'),
    ]

    operations = [
    ]
