# Generated by Django 3.0.5 on 2020-04-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_post_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='perfil',
            new_name='profile',
        ),
    ]
