# Generated by Django 2.2.5 on 2019-12-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_merge_20191225_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=1354297504, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('2BO', 'To_be_open'), ('F', 'Finished'), ('O', 'Open'), ('C', 'Close')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('W', 'Winner'), ('2BA', 'To_be_accepted'), ('R', 'Refused')], default='2BA', max_length=3),
        ),
    ]
