# Generated by Django 3.0.5 on 2020-04-30 03:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20200423_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='0', max_length=30), blank=True, default=list, size=50),
        ),
        migrations.AddField(
            model_name='post',
            name='receivedBenefit',
            field=models.BooleanField(default=False, verbose_name='Has received benefit ?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='data4Company',
            field=models.CharField(blank=True, max_length=26, verbose_name='Data company needs to give benefit'),
        ),
    ]
