# Generated by Django 2.2.5 on 2019-12-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20191225_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='stockW',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('2BO', 'To_be_open'), ('C', 'Close'), ('O', 'Open')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('W', 'Winner'), ('F', 'Finished'), ('R', 'Refused'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
    ]
