# Generated by Django 3.0.4 on 2020-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20200430_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=140733207849296, max_length=255, unique=True),
        ),
    ]
