# Generated by Django 3.0.4 on 2020-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200510_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finaliza'),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=140733020481872, max_length=255, unique=True),
        ),
    ]
