# Generated by Django 3.0.4 on 2020-05-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200504_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=140715107854672, max_length=255, unique=True),
        ),
    ]
