# Generated by Django 2.2.5 on 2019-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20191225_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140727210842448, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('2BO', 'To_be_open'), ('C', 'Close'), ('O', 'Open')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('W', 'Winner'), ('2BA', 'To_be_accepted'), ('F', 'Finished'), ('R', 'Refused')], default='2BA', max_length=3),
        ),
    ]
