# Generated by Django 3.0.5 on 2020-05-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_auto_20200513_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
