# Generated by Django 3.0.5 on 2020-05-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20200514_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exchange_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Code to recieve benefit'),
        ),
    ]
