# Generated by Django 3.0.4 on 2020-05-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_post_exchange_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='instastorypublication',
            name='image',
        ),
    ]
