# Generated by Django 2.2.5 on 2019-12-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20191228_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140727019280720, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('2BO', 'To_be_open'), ('F', 'Finished'), ('O', 'Open'), ('C', 'Close')], default='O', max_length=3),
        ),
    ]
