# Generated by Django 3.0.7 on 2020-07-18 17:50

from django.db import migrations, models
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_post_exchange_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instastorypublication',
            name='processedImage',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='instastorypublication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.path_and_rename),
        ),
    ]
