# Generated by Django 3.0.4 on 2020-05-27 00:47

from django.db import migrations, models
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_auto_20200524_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instastorypublication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.path_and_rename),
        ),
    ]
