# Generated by Django 3.0.4 on 2020-05-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_auto_20200530_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Event_Image/'),
        ),
        migrations.AddField(
            model_name='instastorypublication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Events_Users_Storys/'),
        ),
    ]
