# Generated by Django 2.2.5 on 2019-12-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_auto_20191228_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('2BO', 'To_be_open'), ('F', 'Finished')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('R', 'Refused'), ('2BA', 'To_be_accepted'), ('W', 'Winner'), ('F', 'Finished')], default='2BA', max_length=3),
        ),
    ]
