# Generated by Django 2.2.5 on 2019-12-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_auto_20191228_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('C', 'Close'), ('O', 'Open'), ('F', 'Finished'), ('2BO', 'To_be_open')], default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('R', 'Refused'), ('2BA', 'To_be_accepted'), ('W', 'Winner')], default='2BA', max_length=3),
        ),
    ]
