# Generated by Django 3.0.4 on 2020-05-31 20:10

from django.db import migrations, models
import eventos.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_auto_20200531_1710'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='event',
        #     name='image',
        #     field=models.ImageField(blank=True, null=True, upload_to='events/'),)
        # ),
        migrations.AddField(
            model_name='instastorypublication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.path_and_rename),)
        # ),
        # migrations.AddField(
        #     model_name='instastorypublication',
        #     name='processedImage',
        #     field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        # ),
    ]
