# Generated by Django 2.2.5 on 2019-12-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20191226_0526'),
        ('eventos', '0018_auto_20191228_2154'),
    ]

    operations = [
    ]
