# Generated by Django 2.2.5 on 2019-12-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0019_merge_20191229_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=1354297504, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('2BO', 'To_be_open'), ('C', 'Close'), ('O', 'Open'), ('F', 'Finished')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('W', 'Winner'), ('R', 'Refused'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
    ]
