# Generated by Django 2.2.5 on 2020-01-02 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0020_auto_20191229_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 5', regex='^.{5}$')]),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Finished'), ('2BO', 'To_be_open'), ('C', 'Close')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('R', 'Refused'), ('W', 'Winner')], default='2BA', max_length=3),
        ),
    ]
