# Generated by Django 2.2.5 on 2020-01-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0021_auto_20200102_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('2BO', 'To_be_open'), ('C', 'Close'), ('O', 'Open')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('R', 'Refused'), ('F', 'Finished'), ('W', 'Winner'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
    ]
