# Generated by Django 2.2.5 on 2020-01-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0022_auto_20200105_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrelations',
            name='notificationToken',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=8532160, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Finished'), ('C', 'Close'), ('2BO', 'To_be_open')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('W', 'Winner'), ('F', 'Finished'), ('2BA', 'To_be_accepted'), ('R', 'Refused')], default='2BA', max_length=3),
        ),
    ]
