# Generated by Django 2.2.5 on 2020-01-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0025_auto_20200109_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('C', 'Close'), ('2BO', 'To_be_open'), ('O', 'Open'), ('F', 'Finished')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('W', 'Winner'), ('R', 'Refused'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
    ]
