# Generated by Django 2.2.5 on 2020-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_auto_20200109_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('R', 'Refused'), ('W', 'Winner'), ('2BA', 'To_be_accepted'), ('F', 'Finished')], default='2BA', max_length=3),
        ),
    ]
