# Generated by Django 2.2.5 on 2020-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0026_auto_20200109_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('2BO', 'To_be_open'), ('O', 'Open'), ('C', 'Close')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('R', 'Refused'), ('W', 'Winner'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
    ]
