# Generated by Django 2.2.5 on 2020-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0027_auto_20200109_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('O', 'Open'), ('2BO', 'To_be_open'), ('C', 'Close')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('R', 'Refused'), ('2BA', 'To_be_accepted'), ('F', 'Finished'), ('W', 'Winner')], default='2BA', max_length=3),
        ),
    ]
