# Generated by Django 2.2.5 on 2020-01-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0028_auto_20200109_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('2BO', 'To_be_open'), ('C', 'Close'), ('F', 'Finished'), ('O', 'Open')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('W', 'Winner'), ('2BA', 'To_be_accepted'), ('F', 'Finished'), ('R', 'Refused')], default='2BA', max_length=3),
        ),
    ]
