# Generated by Django 2.2.5 on 2020-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0032_auto_20200111_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='status',
            field=models.CharField(choices=[('2BO', 'To_be_open'), ('O', 'Open'), ('C', 'Close'), ('F', 'Finished')], default='2BO', max_length=3),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('W', 'Winner'), ('F', 'Finished'), ('R', 'Refused')], default='2BA', max_length=3),
        ),
    ]
