# Generated by Django 2.2.5 on 2020-01-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0033_auto_20200111_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140727211366736, max_length=255, unique=True),
        ),
    ]
