# Generated by Django 2.2.5 on 2020-01-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0034_auto_20200121_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=8532160, max_length=255, unique=True),
        ),
    ]
