# Generated by Django 2.2.5 on 2020-02-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_likes'),
        ('eventos', '0035_auto_20200128_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaStoryPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('updloader', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='posts',
            field=models.ManyToManyField(blank=True, to='eventos.InstaStoryPublication', verbose_name='publicaciones'),
        ),
        migrations.DeleteModel(
            name='fotos',
        ),
    ]
