# Generated by Django 2.2.5 on 2020-02-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0036_auto_20200226_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrelations',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.InstaStoryPublication'),
        ),
        migrations.AlterField(
            model_name='instastorypublication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Events_Users_Storys/'),
        ),
    ]
