# Generated by Django 2.2.5 on 2020-02-28 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0037_auto_20200228_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrelations',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.eventpost'),
        ),
    ]
