# Generated by Django 2.2.5 on 2020-02-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0038_auto_20200228_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrelations',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventos.InstaStoryPublication'),
        ),
    ]
