# Generated by Django 2.2.5 on 2020-02-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0039_auto_20200228_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instastorypublication',
            name='updloader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
