# Generated by Django 2.2.5 on 2020-02-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0040_auto_20200228_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instastorypublication',
            old_name='updloader',
            new_name='person',
        ),
    ]
