# Generated by Django 2.2.5 on 2020-02-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0042_auto_20200228_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Event_Image/'),
        ),
    ]
