# Generated by Django 2.2.5 on 2020-03-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0043_eventpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrelations',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.InstaStoryPublication'),
        ),
    ]
