# Generated by Django 2.2.5 on 2020-03-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0044_auto_20200306_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=1705898144, max_length=255, unique=True),
        ),
    ]
