# Generated by Django 2.2.5 on 2020-03-30 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0045_auto_20200329_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='code',
        ),
    ]
