# Generated by Django 3.0.4 on 2020-04-15 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0046_remove_eventpost_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(choices=[('A', 'Short'), ('B', 'Long'), ('T', 'Test')], default='A', max_length=3)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Event_Image/')),
                ('slug', models.SlugField(default=140733077498192, max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('2BO', 'To_be_open'), ('O', 'Open'), ('C', 'Close'), ('F', 'Finished')], default='2BO', max_length=3)),
                ('stock', models.IntegerField(default=50)),
                ('scoring', models.IntegerField(default=0)),
                ('activeParticipants', models.IntegerField(default=0)),
                ('benefitDescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='How to retrieve benefit')),
                ('eventOwner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('2BA', 'To_be_accepted'), ('W', 'Winner'), ('F', 'Finished'), ('R', 'Refused')], default='2BA', max_length=3)),
                ('notificationToken', models.CharField(blank=True, max_length=255, null=True)),
                ('data4Company', models.CharField(blank=True, max_length=26, verbose_name='Data to save')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.Event')),
            ],
            options={
                'ordering': ['-createTime'],
            },
        ),
        migrations.RemoveField(
            model_name='postrelations',
            name='event',
        ),
        migrations.RemoveField(
            model_name='postrelations',
            name='person',
        ),
        migrations.RemoveField(
            model_name='postrelations',
            name='story',
        ),
        migrations.AlterField(
            model_name='instastorypublication',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='eventpost',
        ),
        migrations.DeleteModel(
            name='postrelations',
        ),
        migrations.AddField(
            model_name='post',
            name='instagramStory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.InstaStoryPublication'),
        ),
        migrations.AddField(
            model_name='post',
            name='person',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='posts',
            field=models.ManyToManyField(blank=True, to='eventos.InstaStoryPublication', verbose_name='publicaciones'),
        ),
        migrations.AddField(
            model_name='event',
            name='usersWinners',
            field=models.ManyToManyField(blank=True, related_name='_event_usersWinners_+', to=settings.AUTH_USER_MODEL, verbose_name='list of users Winners'),
        ),
    ]
