# Generated by Django 2.2.5 on 2020-04-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0046_remove_eventpost_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text to retrieve user information'),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='type_ev',
            field=models.CharField(choices=[('A', 'Short'), ('B', 'Long'), ('T', 'Test')], default='A', max_length=3),
        ),
        migrations.AddField(
            model_name='postrelations',
            name='user_info',
            field=models.CharField(blank=True, max_length=26, verbose_name='Data to save'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=1682239648, max_length=255, unique=True),
        ),
    ]
