# Generated by Django 3.0.4 on 2020-04-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20200302_0451'),
        ('eventos', '0046_remove_eventpost_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrelations',
            name='winer_code',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='owner_ev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text to retrieve user information'),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='type_ev',
            field=models.CharField(choices=[('A', 'Short'), ('B', 'Long'), ('T', 'Test')], default='A', max_length=3),
        ),
        migrations.AddField(
            model_name='postrelations',
            name='user_info',
            field=models.CharField(blank=True, max_length=26, verbose_name='Data to save'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140731296819536, max_length=255, unique=True),
        ),
    ]
