# Generated by Django 3.0.4 on 2020-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0047_auto_20200408_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140731290724688, max_length=255, unique=True),
        ),
    ]
