# Generated by Django 2.2.5 on 2020-04-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200407_1609'),
        ('eventos', '0047_auto_20200404_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrelations',
            name='winer_code',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='owner_ev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=1671491744, max_length=255, unique=True),
        ),
    ]
