# Generated by Django 3.0.4 on 2020-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200408_2210'),
        ('eventos', '0048_auto_20200408_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpost',
            old_name='owner_ev',
            new_name='eventOwner',
        ),
        migrations.RenameField(
            model_name='eventpost',
            old_name='type_ev',
            new_name='eventType',
        ),
        migrations.RemoveField(
            model_name='eventpost',
            name='users_winners',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='usersWinners',
            field=models.ManyToManyField(blank=True, related_name='_eventpost_usersWinners_+', to='accounts.user', verbose_name='list of users Winners'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140718859331920, max_length=255, unique=True),
        ),
    ]
