# Generated by Django 3.0.4 on 2020-04-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0049_auto_20200409_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrelations',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.EventPost'),
        ),
    ]
