# Generated by Django 3.0.4 on 2020-04-09 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0051_auto_20200409_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='eventOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='slug',
            field=models.SlugField(default=140718550133072, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_eventpost_users_+', to=settings.AUTH_USER_MODEL, verbose_name='list of users'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='usersWinners',
            field=models.ManyToManyField(blank=True, related_name='_eventpost_usersWinners_+', to=settings.AUTH_USER_MODEL, verbose_name='list of users Winners'),
        ),
        migrations.AlterField(
            model_name='instastorypublication',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.EventPost'),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='person',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
