# Generated by Django 2.2 on 2019-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=94445579337984, max_length=255, unique=True),
        ),
    ]
