# Generated by Django 2.2 on 2019-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0002_auto_20190915_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=94087688839424, max_length=255, unique=True),
        ),
    ]
