# Generated by Django 2.2 on 2019-09-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0003_auto_20190916_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=94161401823488, max_length=255, unique=True),
        ),
    ]
