# Generated by Django 2.2.5 on 2019-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0004_auto_20190916_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=8515776, max_length=255, unique=True),
        ),
    ]
