# Generated by Django 2.2.5 on 2019-11-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0005_auto_20190917_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='barpost',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
