# Generated by Django 2.2.5 on 2019-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0006_barpost_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140704070867280, max_length=255, unique=True),
        ),
    ]
