# Generated by Django 2.2.5 on 2019-11-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0007_auto_20191123_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140704211573072, max_length=255, unique=True),
        ),
    ]
