# Generated by Django 2.2.5 on 2019-11-23 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0008_auto_20191123_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barpost',
            old_name='is_finalized',
            new_name='isFinalized',
        ),
        migrations.AddField(
            model_name='barpost',
            name='usersWinners',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=1, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140703762717008, max_length=255, unique=True),
        ),
    ]
