# Generated by Django 2.2.5 on 2019-11-23 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BarEvento', '0009_auto_20191123_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140704216029520, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='barpost',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_barpost_users_+', to=settings.AUTH_USER_MODEL, verbose_name='list of users'),
        ),
        migrations.RemoveField(
            model_name='barpost',
            name='usersWinners',
        ),
        migrations.AddField(
            model_name='barpost',
            name='usersWinners',
            field=models.ManyToManyField(blank=True, related_name='_barpost_usersWinners_+', to=settings.AUTH_USER_MODEL, verbose_name='list of users Winners'),
        ),
    ]
