# Generated by Django 2.2.5 on 2019-11-24 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BarEvento', '0010_auto_20191123_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barpost',
            old_name='isFinalized',
            new_name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='barpost',
            name='usersWinners',
        ),
        migrations.AddField(
            model_name='barpost',
            name='users_winners',
            field=models.ManyToManyField(blank=True, related_name='_barpost_users_winners_+', to=settings.AUTH_USER_MODEL, verbose_name='list of users Winners'),
        ),
    ]
