# Generated by Django 2.2.5 on 2019-12-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0013_auto_20191202_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140717957355856, max_length=255, unique=True),
        ),
    ]
