# Generated by Django 2.2.5 on 2019-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0016_auto_20191206_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrelations',
            name='status',
            field=models.IntegerField(choices=[('Winner end', '2'), ('Winner new', '1'), ('To be accepted', '0'), ('Refused', '0')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=1919676576, max_length=255, unique=True),
        ),
    ]
