# Generated by Django 2.2.5 on 2019-12-10 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BarEvento', '0017_auto_20191210_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=5, null=True)),
                ('winer_code', models.CharField(max_length=20)),
                ('invite_reason', models.CharField(max_length=6)),
                ('status', models.IntegerField(choices=[('Winner_end', '2'), ('Winner_new', '1'), ('To_be_accepted', '0'), ('Refused', '3')], default='To_be_accepted', max_length=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='BarEvento.BarPost')),
                ('person', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createTime'],
            },
        ),
        migrations.DeleteModel(
            name='EventRelations',
        ),
    ]
