# Generated by Django 2.2.5 on 2019-12-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0018_auto_20191210_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('Refused', '3'), ('To_be_accepted', '0'), ('Winner_end', '2'), ('Winner_new', '1')], default='To_be_accepted', max_length=1),
        ),
    ]
