# Generated by Django 2.2.5 on 2019-12-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0014_auto_20191203_2134'),
        ('BarEvento', '0019_auto_20191210_2101'),
    ]

    operations = [
    ]
