# Generated by Django 2.2.5 on 2019-12-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0021_auto_20191210_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrelations',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='postrelations',
            name='winer_code',
        ),
        migrations.AddField(
            model_name='postrelations',
            name='winner_code',
            field=models.CharField(default=0, max_length=20, verbose_name='Code to Retrieve'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140717912594768, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='invite_reason',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('W', 'Winner'), ('F', 'Finished'), ('R', 'Refused'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
    ]
