# Generated by Django 2.2.5 on 2019-12-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0022_auto_20191215_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrelations',
            name='code',
        ),
        migrations.RemoveField(
            model_name='postrelations',
            name='invite_reason',
        ),
        migrations.RemoveField(
            model_name='postrelations',
            name='is_finalized',
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('R', 'Refused'), ('W', 'Winner'), ('2BA', 'To_be_accepted'), ('F', 'Finished')], default='2BA', max_length=3),
        ),
    ]
