# Generated by Django 2.2.5 on 2019-12-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0022_auto_20191212_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrelations',
            name='code',
        ),
        migrations.RemoveField(
            model_name='postrelations',
            name='invite_reason',
        ),
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140717919607120, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('R', 'Refused'), ('W', 'Winner'), ('2BA', 'To_be_accepted')], default='2BA', max_length=3),
        ),
    ]
