# Generated by Django 2.2.5 on 2019-12-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0023_auto_20191215_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140718049761616, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('W', 'Winner'), ('R', 'Refused'), ('F', 'Finished')], default='2BA', max_length=3),
        ),
    ]
