# Generated by Django 2.2.5 on 2019-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0024_auto_20191215_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrelations',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=140727410923856, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('F', 'Finished'), ('W', 'Winner'), ('R', 'Refused')], default='2BA', max_length=3),
        ),
    ]
