# Generated by Django 2.2.5 on 2019-12-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0025_auto_20191218_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('W', 'Winner'), ('R', 'Refused'), ('F', 'Finished')], default='2BA', max_length=3),
        ),
    ]
