# Generated by Django 2.2.5 on 2019-12-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarEvento', '0026_auto_20191218_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barpost',
            name='slug',
            field=models.SlugField(default=1715400864, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='postrelations',
            name='status',
            field=models.CharField(choices=[('2BA', 'To_be_accepted'), ('R', 'Refused'), ('W', 'Winner'), ('F', 'Finished')], default='2BA', max_length=3),
        ),
    ]
