version: 2.1

jobs:
  build:
    docker:
    - image: circleci/python:3.7.3  # primary container for the build job
    - image: postgres:10
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: circle_test
        POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install -r requirements.txt
      - run:
          name: Run tests
          command: python manage.py test
workflows:
  main:
    jobs:
      - build
