version: 2.1

jobs:
  build:
    docker:
    - image: circleci/python:3.7.3  # primary container for the build job
    - image: postgres:10
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: circle_test
        POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install -r requirements.txt
      - run:
          name: Install test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Configure test reporter
          command: ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: |
            coverage run manage.py test --settings=core.settings.test
            coverage xml
      - run:
          name: Submit test results
          command: ./cc-test-reporter after-build
workflows:
  main:
    jobs:
      - build
