# Generated by Django 2.2.5 on 2019-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_hola'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scoring',
            field=models.IntegerField(default=0),
        ),
    ]
