# Generated by Django 2.2.5 on 2019-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
