# Generated by Django 3.0.4 on 2020-04-22 00:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200416_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='eventWatchList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='0', max_length=30), default='{}', size=50),
            preserve_default=False,
        ),
    ]
