# Generated by Django 2.2.5 on 2020-01-09 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191228_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 19, 26, 54, 995740)),
        ),
    ]
