# Generated by Django 2.2.5 on 2020-01-09 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
