# Generated by Django 2.2.5 on 2020-01-11 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200111_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
