# Generated by Django 2.2.5 on 2020-01-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200111_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthDate',
        ),
    ]
