# Generated by Django 2.2.5 on 2020-01-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='missing', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='missing', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='missing', max_length=125),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(default=0, max_length=22),
        ),
    ]
