# Generated by Django 2.2.5 on 2020-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200120_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of followers'),
        ),
    ]
