# Generated by Django 2.2.5 on 2020-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='scoring',
        ),
        migrations.AddField(
            model_name='profile',
            name='scoring',
            field=models.IntegerField(blank=True, default=0, verbose_name='Overall event score'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, default=0, max_length=22),
        ),
    ]
