# Generated by Django 2.2.5 on 2020-02-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200226_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.FloatField(blank=True, null=True, verbose_name='Promediated likes per publication'),
        ),
    ]
