# Generated by Django 2.2.5 on 2020-03-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_likes'),
        ('accounts', '0016_auto_20200227_2049'),
    ]

    operations = [
    ]
