# Generated by Django 3.0.4 on 2020-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_merge_20200302_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'User'), (2, 'Company'), (3, 'Validator')], default=1, max_length=3),
        ),
    ]
