# Generated by Django 2.2.5 on 2020-04-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200404_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'User'), (2, 'Company'), (3, 'Validator')], default=1, max_length=3),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
